@startuml
BPF -> UC: RRCConnectionRequest 
note left: BC_CCCH,1,scene.gnbId.cellId.crnti 
UC -> GAS: GidAllocateRequest
note left: GidAllocateRequest(UCS_GAS,1,msId.pno) 
GAS --> UC: GidAllocateRespons
note right: UCS_GAS,2,msId.pno
UC -> HRRM: SrbAdmitReques
note left: UCS_CMS_UE,1,gnbId.cellId.cpfueid
UC <-- HRRM: SrbAdmitResponse
note right: UCS_CMS_UE,2,gnbId.cellId.cpfueid
UC -> STS: SrbAdmitReques
note left: UCS_STS_SRB,1,cpfueid
UC -> BPF: UeContextConfigRequest 
note right: BC_UE,1,gnbId.cellId.cpfueid
UC <-- STS: SrbAdmitResponse
note right: UCS_STS_SRB,2,cpfueid
UC <-- BPF: UeContextConfigResponse 
note left: BC_UE,2,gnbId.cellId.cpfueid
UC -> BPF: UeContextConfigRequest 
note right: BC_CCCH,2,scene.gnbId.cellId.crnti
BPF -> STS: RRCConnectionSetUpComplete 
note left: BC_DCCH,,cpfUeId.ppsId
STS -> UC: RRCConnectionSetUpComplete
note right: UCS_CMS_UE,2,gnbId.cellId.cpfueid
UC -> HRRM: SrbAdmitAcknowledge
note left: UCS_CMS_UE,3,gnbId.cellId.cpfueid  
@enduml
